apiVersion: v1
kind: ServiceAccount
metadata:
  name: krangd
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krangd
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["cnipluginregistrations", "cnimutationrequests"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krangd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krangd
subjects:
  - kind: ServiceAccount
    name: krangd
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: krangd
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: krangd
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: krangd
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: krangd
      tolerations:
        - operator: Exists
          effect: NoSchedule
      containers:
        - name: krangd
          image: fedora:latest
          # command: [ "sleep", "10000" ]
          command: [ "/krangd/krangd", "--log-level=debug" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: krang-bin
              mountPath: /krangd
            - name: host-run
              mountPath: /host/run
            - name: host-netns
              mountPath: /run/netns
              mountPropagation: HostToContainer
            - name: pod-resources
              mountPath: /var/lib/kubelet/pod-resources
              readOnly: true
            - name: cni-bin
              mountPath: /opt/cni/bin
            - name: cni-conf
              mountPath: /etc/cni/net.d
      volumes:
        - name: krang-bin
          hostPath:
            path: /var/lib/krangd
            type: Directory
        - name: host-run
          hostPath:
            path: /run
        - name: host-netns
          hostPath:
            path: /run/netns
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
        - name: cni-conf
          hostPath:
            path: /etc/cni/net.d
