//go:build !ignore_autogenerated

/*
Copyright 2025 The CNI Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNICanary) DeepCopyInto(out *CNICanary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNICanary.
func (in *CNICanary) DeepCopy() *CNICanary {
	if in == nil {
		return nil
	}
	out := new(CNICanary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNICanary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNICanaryList) DeepCopyInto(out *CNICanaryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CNICanary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNICanaryList.
func (in *CNICanaryList) DeepCopy() *CNICanaryList {
	if in == nil {
		return nil
	}
	out := new(CNICanaryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNICanaryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNICanarySpec) DeepCopyInto(out *CNICanarySpec) {
	*out = *in
	out.NetworkRef = in.NetworkRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNICanarySpec.
func (in *CNICanarySpec) DeepCopy() *CNICanarySpec {
	if in == nil {
		return nil
	}
	out := new(CNICanarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNICanaryStatus) DeepCopyInto(out *CNICanaryStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Connectivity != nil {
		in, out := &in.Connectivity, &out.Connectivity
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNICanaryStatus.
func (in *CNICanaryStatus) DeepCopy() *CNICanaryStatus {
	if in == nil {
		return nil
	}
	out := new(CNICanaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIMutationRequest) DeepCopyInto(out *CNIMutationRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIMutationRequest.
func (in *CNIMutationRequest) DeepCopy() *CNIMutationRequest {
	if in == nil {
		return nil
	}
	out := new(CNIMutationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNIMutationRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIMutationRequestList) DeepCopyInto(out *CNIMutationRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CNIMutationRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIMutationRequestList.
func (in *CNIMutationRequestList) DeepCopy() *CNIMutationRequestList {
	if in == nil {
		return nil
	}
	out := new(CNIMutationRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNIMutationRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIMutationRequestSpec) DeepCopyInto(out *CNIMutationRequestSpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	in.Args.DeepCopyInto(&out.Args)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIMutationRequestSpec.
func (in *CNIMutationRequestSpec) DeepCopy() *CNIMutationRequestSpec {
	if in == nil {
		return nil
	}
	out := new(CNIMutationRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIMutationRequestStatus) DeepCopyInto(out *CNIMutationRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIMutationRequestStatus.
func (in *CNIMutationRequestStatus) DeepCopy() *CNIMutationRequestStatus {
	if in == nil {
		return nil
	}
	out := new(CNIMutationRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIPluginRegistration) DeepCopyInto(out *CNIPluginRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIPluginRegistration.
func (in *CNIPluginRegistration) DeepCopy() *CNIPluginRegistration {
	if in == nil {
		return nil
	}
	out := new(CNIPluginRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNIPluginRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIPluginRegistrationList) DeepCopyInto(out *CNIPluginRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CNIPluginRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIPluginRegistrationList.
func (in *CNIPluginRegistrationList) DeepCopy() *CNIPluginRegistrationList {
	if in == nil {
		return nil
	}
	out := new(CNIPluginRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNIPluginRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIPluginRegistrationSpec) DeepCopyInto(out *CNIPluginRegistrationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIPluginRegistrationSpec.
func (in *CNIPluginRegistrationSpec) DeepCopy() *CNIPluginRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(CNIPluginRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIPluginRegistrationStatus) DeepCopyInto(out *CNIPluginRegistrationStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodePluginStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIPluginRegistrationStatus.
func (in *CNIPluginRegistrationStatus) DeepCopy() *CNIPluginRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(CNIPluginRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIValidation) DeepCopyInto(out *CNIValidation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIValidation.
func (in *CNIValidation) DeepCopy() *CNIValidation {
	if in == nil {
		return nil
	}
	out := new(CNIValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNIValidation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIValidationList) DeepCopyInto(out *CNIValidationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CNIValidation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIValidationList.
func (in *CNIValidationList) DeepCopy() *CNIValidationList {
	if in == nil {
		return nil
	}
	out := new(CNIValidationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CNIValidationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIValidationSpec) DeepCopyInto(out *CNIValidationSpec) {
	*out = *in
	out.NetworkRef = in.NetworkRef
	out.CanaryRef = in.CanaryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIValidationSpec.
func (in *CNIValidationSpec) DeepCopy() *CNIValidationSpec {
	if in == nil {
		return nil
	}
	out := new(CNIValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIValidationStatus) DeepCopyInto(out *CNIValidationStatus) {
	*out = *in
	if in.PluginTypes != nil {
		in, out := &in.PluginTypes, &out.PluginTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ValidatedAt.DeepCopyInto(&out.ValidatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIValidationStatus.
func (in *CNIValidationStatus) DeepCopy() *CNIValidationStatus {
	if in == nil {
		return nil
	}
	out := new(CNIValidationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePluginStatus) DeepCopyInto(out *NodePluginStatus) {
	*out = *in
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePluginStatus.
func (in *NodePluginStatus) DeepCopy() *NodePluginStatus {
	if in == nil {
		return nil
	}
	out := new(NodePluginStatus)
	in.DeepCopyInto(out)
	return out
}
