apiVersion: k8s.cni.cncf.io/v1alpha1
kind: CNIMutationRequest
metadata:
  name: mutate-arpfilter
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      app: demotuning
  cniType: tuning
  interface: eth0
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "update-tuning",
      "plugins": [
        {
          "type": "passthru"
        },
        {
          "type": "tuning",
          "sysctl": {
            "net.ipv4.conf.eth0.arp_filter": "1"
          }
        }
      ]
    }
