apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demotuning
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demotuning
  template:
    metadata:
      labels:
        app: demotuning
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
